commands:
    build: yarn build
    unitTest: yarn test
    lint: null
    localization: yarn localize
notifications:
    deployNotifyEmailFailure: mpeterson@adobe.com
    deployNotifyEmailSuccess: mpeterson@adobe.com
runIntegrationTests:
    runTest: false
    command: null
runLocalization:
  enabled: true 
  commitToForks: true
  runPlusOn: ['prod']
  localizationFirst: false
vaultPath: null
runPerformanceTests:
    runTest: null
install:
    registry:
        - npm-aaui-release
publishToArtifactory:
    enabled: true
    branchToPublish: prod
skmsChangeModelId: "119769"
sonarQube:
    skipBuildFailure: false
buildReport:
    stage:
        - storybook: { path: 
"/solutions/AnalyticsUI-prism/static-assets/storybook/index.html", name: "Storybook" }
# pipelineFeaturesEnabled when set to true enables support for SPA Pipeline features
# Info about pipelineFeaturesEnabled is available at : https://wiki.corp.adobe.com/display/engage/Introduction+to+SPA-Pipeline-Tools
