name: PR Checks

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install Dependencies 📦
              run: yarn install

            - name: Lint 🧼
              run: yarn lint

            - name: Check Chart if types modified
              id: check_chart_types
              run: |
                set -eo pipefail
                echo "Fetching PR details..."
                FILES_JSON=$(gh pr view ${{ github.event.pull_request.number }} --json files)
                echo "Looking for modifications in Chart.ts..."
                CHART_TYPES_MODIFIED=$(echo "$FILES_JSON" | jq -r '.files[].filename' | grep -F "Chart.ts") || true
                
                if [ -n "$CHART_TYPES_MODIFIED" ]; then
                  echo "Chart.ts has been modified."
                  echo "chart_types_modified=true" >> $GITHUB_ENV
                else
                  echo "Chart.ts has not been modified."
                  echo "chart_types_modified=false" >> $GITHUB_ENV
                fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Add PR documentation requirements
              if: env.chart_types_modified == 'true'
              run: |
                PR_DESCRIPTION=$(gh pr view ${{ github.event.pull_request.number }} --json body -q .body)
                NEW_DESCRIPTION="${PR_DESCRIPTION}\n- [ ] Documentation has been updated for modified components."
          
                gh pr edit ${{ github.event.pull_request.number }} --body "$NEW_DESCRIPTION"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Build 🛠️
              run: yarn build
