name: PR comment
on: issue_comment

permissions:
    contents: write
    pull-requests: write
    repository-projects: write

jobs:
    pr_commented:
        name: PR comment workflow
        if: |
            github.event.issue.pull_request &&
            github.repository == 'adobe/react-spectrum-charts' &&
            github.event.comment.author_association == 'MEMBER' &&
            contains(github.event.comment.body, 'GET_BUILD')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              run: echo ${{ github.event.issue.pull_request.head }}
