name: Publish Storybook to GitHub Pages
# This action runs when a branch has been merged to main.

on:
    push:
        branches:
            - main

permissions:
    pages: write
    id-token: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install Dependencies 📦
              run: yarn install

            - name: Build Storybook
              run: yarn build:storybook

            - name: Create and Checkout 'gh-pages' branch
              run: |
                git checkout --orphan gh-pages
                git rm -rf .
                git reset -- 'PR-*'
                git commit --allow-empty -m "Initialize gh-pages branch"
                git push origin gh-pages

            - name: Copy 'dist-storybook' to 'gh-pages' branch
              run: |
                cp -r dist-storybook/* .

            - name: Commit and push changes to 'gh-pages' branch
              run: |
                git add -A
                git commit -m "Update gh-pages with latest Storybook build"
                git push origin gh-pages

            - name: Setup Pages
              uses: actions/configure-pages@v3

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  path: './dist-storybook'

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
