name: Publish library

on:
    push:
        tags:
            - 'v*.*.*' # Only trigger on tags that match the pattern 'vX.X.X'

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref_name }}
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  registry-url: 'https://registry.npmjs.org'

            - name: Extract Tag
              id: extract_tag
              run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

            - name: Update Package Version
              run: |
                  # Update the version in package.json
                  tag=${{ steps.extract_tag.outputs.tag }}
                  sed -i "s/\"version\": \".*\"/\"version\": \"$tag\"/" package.json

                  # Commit the changes
                  git config user.name "GitHub Actions"
                  git config user.email "actions@users.noreply.github.com"
                  git add package.json
                  git commit -m "Update package version to $tag"
                  git push
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - name: Install Dependencies
              run: yarn install

            - name: Build
              run: yarn build

            - name: Publish Package
              run: yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
