name: PR Post-Build Sonar
on:
    workflow_run:
        workflows: [PR Build]
        types: [completed]
jobs:
    sonar:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        if: github.event.workflow_run.conclusion == 'success'
        steps:
            - name: Checkout PR code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: 'Download code coverage'
              uses: actions/github-script@v6
              with:
                  script: |
                      let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
                         owner: context.repo.owner,
                         repo: context.repo.repo,
                         run_id: context.payload.workflow_run.id,
                      });
                      let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
                        return artifact.name == "rsc-code-coverage"
                      })[0];
                      let download = await github.rest.actions.downloadArtifact({
                         owner: context.repo.owner,
                         repo: context.repo.repo,
                         artifact_id: matchArtifact.id,
                         archive_format: 'zip',
                      });
                      let fs = require('fs');
                      fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/rsc-code-coverage.zip`, Buffer.from(download.data));

            - name: 'Unzip code coverage'
              run: unzip rsc-code-coverage.zip

            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                  args: >
                      -Dsonar.scm.revision=${{ github.event.workflow_run.head_sha }}
                      -Dsonar.pullrequest.key=${{ github.event.workflow_run.pull_requests[0].number }}
                      -Dsonar.pullrequest.branch=${{ github.event.workflow_run.pull_requests[0].head.ref }}
                      -Dsonar.pullrequest.base=${{ github.event.workflow_run.pull_requests[0].base.ref }}
